name: Build Blurr Android App

  on:
    push:
      branches: [ "main" ] # ou "master" selon le nom de la branche principale
    workflow_dispatch: # Permet de lancer manuellement la compilation

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Donner la permission d'exécution à gradlew
        run: chmod +x gradlew

      - name: Créer le fichier local.properties
        run: |
          touch local.properties
          echo "sdk.dir=$ANDROID_SDK_ROOT" >> local.properties
          echo "GEMINI_API_KEYS=${{ secrets.GEMINI_API_KEYS }}" >> local.properties
        env:
          GEMINI_API_KEYS: ${{ secrets.GEMINI_API_KEYS }}

      - name: Lancer la compilation avec Gradle
        run: ./gradlew assembleDebug

      - name: Téléverser l'APK en tant qu'artefact
        uses: actions/upload-artifact@v4
        with:
          name: blurr-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
