  name: Build Blurr Android App

  on:
    push:
      branches: [ "main" ]
    workflow_dispatch:

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Java (JDK 11)
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Donner la permission d'exécution à gradlew
        run: chmod +x gradlew

      - name: Créer le fichier local.properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" >> local.properties
          echo "GEMINI_API_KEYS=${{ secrets.GEMINI_API_KEYS }}" >> local.properties

      - name: Lancer la compilation avec Gradle
        run: ./gradlew assembleDebug

      - name: Téléverser l'APK en tant qu'artefact
        uses: actions/upload-artifact@v4
        with:
          name: blurr-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
